{
  "formatVersion": "1.1",
  "component": {
    "group": "com.core.sdk",
    "module": "corecore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "corecore-1.0.0.aar",
          "url": "corecore-1.0.0.aar",
          "size": 22615,
          "sha512": "0f92999a38345d152198c797b6622c258fb81705f38aec764f2bc63a4479c2e931d270cad6c5231ccb31fcc1e68c445e0b03d359510f644b3a53c2d9dee4dff7",
          "sha256": "4ab199e87433478c2d7758a445ddfa3383f8094580a29b914c22d65647ae4dfc",
          "sha1": "76b5c10a77018a19d4f64eb013cb277daf65456a",
          "md5": "14f32117abb4d0b0cfcfdca1154df38d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "corecore-1.0.0.aar",
          "url": "corecore-1.0.0.aar",
          "size": 22615,
          "sha512": "0f92999a38345d152198c797b6622c258fb81705f38aec764f2bc63a4479c2e931d270cad6c5231ccb31fcc1e68c445e0b03d359510f644b3a53c2d9dee4dff7",
          "sha256": "4ab199e87433478c2d7758a445ddfa3383f8094580a29b914c22d65647ae4dfc",
          "sha1": "76b5c10a77018a19d4f64eb013cb277daf65456a",
          "md5": "14f32117abb4d0b0cfcfdca1154df38d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "corecore-1.0.0-sources.jar",
          "url": "corecore-1.0.0-sources.jar",
          "size": 6219,
          "sha512": "bdafecb6ad13fdfdcb539d31c8bbdfb41a6bf1d9622669d32e1c7cf7f185568642c3a06850af3b0522365e1a0675e89f8cfff12245aec989f950c78e90877c44",
          "sha256": "76f3c9fbe5a61660940e1a045942ad53198f8b0b8afcaf68b6febdb42f50f7dc",
          "sha1": "6e08a6f5216ab6e8dfdb14f73935cf22a6f932bf",
          "md5": "7eeb8604e8a9e6b417672e76c97b25f9"
        }
      ]
    }
  ]
}
