{
  "formatVersion": "1.1",
  "component": {
    "group": "com.core.sdk",
    "module": "corecore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "corecore-1.0.0.aar",
          "url": "corecore-1.0.0.aar",
          "size": 22615,
          "sha512": "0f92999a38345d152198c797b6622c258fb81705f38aec764f2bc63a4479c2e931d270cad6c5231ccb31fcc1e68c445e0b03d359510f644b3a53c2d9dee4dff7",
          "sha256": "4ab199e87433478c2d7758a445ddfa3383f8094580a29b914c22d65647ae4dfc",
          "sha1": "76b5c10a77018a19d4f64eb013cb277daf65456a",
          "md5": "14f32117abb4d0b0cfcfdca1154df38d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "corecore-1.0.0.aar",
          "url": "corecore-1.0.0.aar",
          "size": 22615,
          "sha512": "0f92999a38345d152198c797b6622c258fb81705f38aec764f2bc63a4479c2e931d270cad6c5231ccb31fcc1e68c445e0b03d359510f644b3a53c2d9dee4dff7",
          "sha256": "4ab199e87433478c2d7758a445ddfa3383f8094580a29b914c22d65647ae4dfc",
          "sha1": "76b5c10a77018a19d4f64eb013cb277daf65456a",
          "md5": "14f32117abb4d0b0cfcfdca1154df38d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "corecore-1.0.0-sources.jar",
          "url": "corecore-1.0.0-sources.jar",
          "size": 6219,
          "sha512": "c8146e5ccbe0b3652e75f77d593671f91666fa1c6ccebfdf57e4c284fb05a7e740b8620923be37337adc69faf12dc604f943ceb77513156af4774137840e2e8e",
          "sha256": "b8d29313469c47caa68462a998987b348cf101484b97c38427e15bd8e0d3b6be",
          "sha1": "a983fc3063b35deca315c70f8ec2db4c30a46107",
          "md5": "b54983d2fb8daee26370d346c51c63a3"
        }
      ]
    }
  ]
}
